export const formTestCases = [
    // Step 0
    {
        desc: "And I leave the Plan Name field blank",
        field: "promoPlanName",
        type: "input",
        step: 0,
        badValue: "",
        goodValue: "beta_promo",
        errorText: "#promoPlanName-helper-text",
        buttons: ["Next"],
    },
    {
        desc: "And I leave the Plan Description field blank",
        field: "promoDescription",
        type: "input",
        step: 0,
        badValue: "",
        goodValue: "Beta promotion 2019",
        errorText: "#promoDescription-helper-text",
        buttons: ["Next"],
    },
    {
        desc: "And I leave the Tenant ID field blank",
        field: "tenantId",
        type: "input",
        step: 0,
        badValue: "",
        goodValue: "1",
        errorText: "#tenantId-helper-text",
        buttons: ["Next"],
    },
    {
        desc: "And I leave the Plan Start Date field blank",
        field: "promoValidityStartTime",
        type: "input",
        step: 0,
        badValue: "",
        goodValue: "2019-05-24T10:30:00",
        errorText: "#promoValidityStartTime-helper-text",
        buttons: ["Next"],
    },
    {
        desc: "And I leave the Plan End Date field blank",
        field: "promoValidityEndTime",
        type: "input",
        step: 0,
        badValue: "",
        goodValue: "2019-05-24T10:30:00",
        errorText: "#promoValidityEndTime-helper-text",
        buttons: ["Next"],
    },
    // Step 1
    {
        desc: "And I leave the Code Prefix field blank",
        field: "codePrefix",
        type: "input",
        step: 1,
        badValue: "",
        goodValue: "beta2019",
        errorText: "#codePrefix-helper-text",
        buttons: ["Back", "Submit"],
    },
    {
        desc: "And I leave the Redemption Type field blank",
        field: "codeUsageType",
        type: "select",
        step: 1,
        badValue: "",
        goodValue: "single-use",
        errorText: "#codeUsageType-helper-text",
        buttons: ["Back", "Submit"],
    },
    {
        desc: "And I leave the Random Characters field blank",
        field: "codeLength",
        type: "input",
        step: 1,
        badValue: "",
        goodValue: "5",
        errorText: "#codeLength-helper-text",
        buttons: ["Back", "Submit"],
        dependencies: { codeUsageType: { type: "select" , value: "single-use" } }
    },
    {
        desc: "And I leave the Redemption Limit field blank",
        field: "redemptionLimit",
        type: "input",
        step: 1,
        badValue: "",
        goodValue: "1",
        errorText: "#redemptionLimit-helper-text",
        buttons: ["Back", "Submit"],
        dependencies: { codeUsageType: { type: "select" , value: "single-use" } }
    },
    {
        desc: "And I leave the Code Count field blank",
        field: "codeCount",
        type: "input",
        step: 1,
        badValue: "",
        goodValue: "1000",
        errorText: "#codeCount-helper-text",
        buttons: ["Back", "Submit"],
        dependencies: { codeUsageType: { type: "select" , value: "single-use" } }
    },
];
